export const USER_LOGIN='/users/login'
export const USER_USERLIST='/users/userlist'
export const USER_USERDELERE='/users/userdelete'
export const USER_USERUPDATE='/users/userupdate'
export const USER_USERSEARCH='/users/usersearch'
export const USER_USERPLIST='/users/userplist'
export const USER_USERREFRESHTOKEN='/users/refreshtoken'
export const USER_USERAVATAR='/users/useravatar'
